### PR TITLE
keep warnings under control

### PR DESCRIPTION
**Pull request by gibix**

### CODE REVIEW

**Comment by lu-zero** [comment]
I'm not seeing warnings here, which warnings are you seeing and which version of rust are you using?

**Comment by gibix** [comment]
```
warning: unreachable pattern                                                                                                                                                  
  --> src/resampler.rs:32:13                                                                                                                                                  
   |                                                                                                                                                                          
31 |             RESAMPLER_ERR_OVERFLOW => Error::Overflow,                                                                                                                   
   |             ---------------------- matches any value                                                                                                                     
32 |             _ => unreachable!(),                                                                                                                                         
   |             ^ unreachable pattern                                                                                                                                        
   |                                                                                                                                                                          
   = note: #[warn(unreachable_patterns)] on by default                                                                                                                        
                                                                                                                                                                              
warning: unused variable: `RESAMPLER_ERR_OVERFLOW`                                                                                                                            
  --> src/resampler.rs:31:13                                                                                                                                                  
   |                                                                                                                                                                          
31 |             RESAMPLER_ERR_OVERFLOW => Error::Overflow,                                                                                                                   
   |             ^^^^^^^^^^^^^^^^^^^^^^ help: consider using `_RESAMPLER_ERR_OVERFLOW` instead                                                                                
   |                                                                                                                                                                          
   = note: #[warn(unused_variables)] on by default                                                                                                                            
                                                                                                                                                                              
warning: variable `RESAMPLER_ERR_OVERFLOW` should have a snake case name such as `resampler_err_overflow`                                                                     
  --> src/resampler.rs:31:13                                                                                                                                                  
   |                                                                                                                                                                          
31 |             RESAMPLER_ERR_OVERFLOW => Error::Overflow,                                                                                                                   
   |             ^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                       
   |
   = note: #[warn(non_snake_case)] on by default
```

**Comment by lu-zero** [comment]
Which version of bindgen are you using and what is it producing?

``` rust
pub const RESAMPLER_ERR_SUCCESS: _bindgen_ty_1 = 0;
pub const RESAMPLER_ERR_ALLOC_FAILED: _bindgen_ty_1 = 1;
pub const RESAMPLER_ERR_BAD_STATE: _bindgen_ty_1 = 2;
pub const RESAMPLER_ERR_INVALID_ARG: _bindgen_ty_1 = 3;
pub const RESAMPLER_ERR_PTR_OVERLAP: _bindgen_ty_1 = 4;
pub const RESAMPLER_ERR_OVERFLOW: _bindgen_ty_1 = 5;
pub const RESAMPLER_ERR_MAX_ERROR: _bindgen_ty_1 = 6;
```

**Comment by gibix** [comment]
Bindgen: 0.33.2
Speex: [1.2.0](https://www.archlinux.org/packages/extra/x86_64/speex/)
Rustc: nighlty,stable

bindgen /usr/include/speex/speex_resampler.h | rg "pub const RESAMPLER_ERR"
```rust
pub const RESAMPLER_ERR_SUCCESS: _bindgen_ty_1 = 0;                                                                                                                           
pub const RESAMPLER_ERR_ALLOC_FAILED: _bindgen_ty_1 = 1;
pub const RESAMPLER_ERR_BAD_STATE: _bindgen_ty_1 = 2;
pub const RESAMPLER_ERR_INVALID_ARG: _bindgen_ty_1 = 3;
pub const RESAMPLER_ERR_PTR_OVERLAP: _bindgen_ty_1 = 4;
pub const RESAMPLER_ERR_MAX_ERROR: _bindgen_ty_1 = 5;
```

**Comment by lu-zero** [comment]
@tmatth the speexdsp provided by speex itself does have a misleading modversion?

**Comment by lu-zero** [comment]
I would drop this. it is hiding the problem sadly :/

**Pull request closed without merging**
