### PR TITLE
Make resampler safe

### PR DESCRIPTION
**Pull request by Luni-4**
This PR makes the resampler safe

### CODE REVIEW

**Comment by lu-zero** [comment]
Looks promising :)

**Comment by Luni-4** [comment]
@lu-zero, before fixing the tests, do you think I should implement the first item of #15 along with this PR?

**Comment by lu-zero** [comment]
> Resampler is completely safe now! Yay! xD
> 
> @lu-zero, before fixing the tests, do you think I should implement the first item of #15 along with this PR?

This can land as-is now :)

**Comment by Luni-4** [comment]
> > Resampler is completely safe now! Yay! xD
> > @lu-zero, before fixing the tests, do you think I should implement the first item of #15 along with this PR?
> 
> This can land as-is now :)

Ok, thanks for merging it! :)

**Pull request merged**
