### PR TITLE
Make sinc_table and mem fields a vector

### LINKED ISSUE #16: Replace the explicit memory reallocation of the  buffers:
- [ ] Make the `sinc_table` field a vector and reallocate it as needed.
- [ ] Make the `mem` field a vector and reallocate it as needed.

### PR DESCRIPTION
**Pull request by Luni-4**
This PR fixes #16. 

Thanks in advance for the review!

### CODE REVIEW

**Comment by lu-zero** [comment]
if you could split the rustfmt pass from the functional changes would be great.

**Comment by lu-zero** [comment]
It is surely a step in the right direction, thank you a lot.

It can be refined later.

**Comment by Luni-4** [comment]
> It is surely a step in the right direction, thank you a lot.

Thank you for merging my PR! 

> It can be refined later.

If you could tell me what I should redefine in particular, I would try to implement it.

**Comment by lu-zero** [comment]
The first thing I thought of when reviewing is to drop the misleading types (word16 is actually a float), but it should happen in another PR anyway :)

**Comment by Luni-4** [comment]
> The first thing I thought of when reviewing is to drop the misleading types (word16 is actually a float), but it should happen in another PR anyway :)

Ok, got it. I can do another PR subsequently :)

**Pull request merged**
