### PR TITLE
replaced avx instructions with sse instructions

### PR DESCRIPTION
**Pull request by khodzha**
right now interpolation in doubles is a mess of AVX(_m256*) and SSE instructions
since feature is called sse this commit removes everything AVX for now

### CODE REVIEW

**Comment by khodzha** [comment]
side note:
`_mm_hadd_ps` / `_mm_hadd_pd` [are](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_hadd_p&expand=2942,2946) of `SSE3` instruction set and since feature is called `sse2` i suppose we should replace hadds with something else or bump it to sse3?

**Comment by khodzha** [comment]
right now resampler would fail to compile on a target with SSE2 and no AVX because we use `target_feature=sse2` but some instructions used are from SSE3 (hadds) or AVX (everything _m256*)

the code behaves the same as before, i just replaced AVX instructions (well probably performance is worse)

**Comment by Luni-4** [comment]
@khodzha 

Would it be possible to create three different files? 
Something like:

- `target_feature=sse2` --> resampler_sse2.rs
- `target_feature=sse3` --> resampler_sse3.rs
- `target_feature=avx2` --> resampler_avx2.rs

So the codes of each optimization are not mixed together and we can evaluate and test them separately.

**Comment by khodzha** [comment]
no problem, my question is should i replace hadds (they are from sse3) with something else to support only sse2 or just bump sse2 target_feature to sse3

**Comment by Luni-4** [comment]
> no problem, my question is should i replace hadds (they are from sse3) with something else to support only sse2 or just bump sse2 target_feature to sse3

I'm not expert with this kind of instructions, so I could say something wrong, sorry in advance :)

Perhaps in the `resampler_sse2.rs` we could use **only** sse2 instructions and in the `resampler_sse3.rs` **only** sse3 instructions. 

Then it would be the user who chooses the set of instructions to be used.

**Comment by khodzha** [comment]
the thing is we dont use anything from `sse3` but horizontal vec sum right now

**Comment by Luni-4** [comment]
> the thing is we dont use anything from `sse3` but horizontal vec sum right now

Hmm, I see. Which is the predominant set of instructions in our code now? sse?

**Comment by Luni-4** [comment]
It would be good create something like [this](https://github.com/xiph/rav1e/blob/c8b3e94da00de44ed2bafa795b8dd3fd5cbec669/src/cpu_features/x86.rs) to choose which set of instructions should be run

**Comment by lu-zero** [comment]
We could start with just avx and sse3, and improve later.

**Comment by khodzha** [comment]
also im not sure why but now i need to run benches with
`RUSTFLAGS='-C target-feature=+sse3' cargo bench -- resampler_simple_rust` for sse instructions to kick in

**Comment by Luni-4** [comment]
Great! Thanks a lot @khodzha! 

> also im not sure why but now i need to run benches with
> `RUSTFLAGS='-C target-feature=+sse3' cargo bench -- resampler_simple_rust` for sse instructions to kick in

Hmm, I think it's correct. Because you're telling to Rust to use the `sse3` feature to run the benchmark with the `sse3` set of  instructions. Can we adopt the following syntax instead?
`cargo bench --features sse3   -- resampler_simple_rust`
`cargo bench --features avx2   -- resampler_simple_rust`

And when we don't specify a feature, the `native` version is run.

**Comment by khodzha** [comment]
i'd think sse3 would be enabled by default since i'm compilling on intel i7-6700k and `target_feature = "sse3"` must evaluate to true on this cpu? idk :shrug:

**Comment by Luni-4** [comment]
True, but perhaps we could adopt the following approach: If you set a feature that enables a set of instructions you don't have, run the `native` feature by default. 
What do you think?

**Comment by khodzha** [comment]
i think thats the proper way but i was assuming this would have been handled by `target_feature` automatically :disappointed:

**Comment by Luni-4** [comment]
You should add the features you have created on the `resampler/Cargo.toml` and set native as default. I think that would fix the problem.

**Comment by lu-zero** [comment]
I guess if the CI survives it can be landed.

**Comment by lu-zero** [comment]
To be sure, @khodzha do you confirm you can rebase+merge on your own?

**Comment by lu-zero** [comment]
To be sure, @khodzha do you confirm you can rebase+merge on your own?

**Comment by khodzha** [comment]
I figured it out
> By default, the Rust compiler produces portable binaries that are able to run on all CPUs of a particular architecture

So thats why it doesnt compile with `target_feature=+sse3` without passing `RUSTFLAGS`

I added `sse3` feature as @Luni-4 suggested
I'm not sure if its okay that I removed `#[cfg(target_feature = "sse3")]` feature gate tho

**Comment by khodzha** [comment]
should be rebased

**Comment by lu-zero** [comment]
We can add runtime selection in another PR I think

**Comment by Luni-4** [comment]
Thanks a lot @khodzha! 

Just replace the commit message word "replaced" with "Replace" and then feel free to merge it :)

Yep, I agree with @lu-zero, we can handle runtime selection in another PR.

**Comment by khodzha** [comment]
i wonder what happens if we go out of bounds (for example when `[f32]` size isnt multiple of 4) :thinking:

**Comment by Luni-4** [comment]
> i wonder what happens if we go out of bounds (for example when `[f32]` size isnt multiple of 4) thinking

Is it possible to create a test to evaluate that case?

**Comment by khodzha** [comment]
i tried loading `vec![1.0, 2.0, 3.0, 4.0, 5.0]` into two `__m128` and the second one had `__m128(5.0, 0.0, 0.000000000000000000000000000000000000000184928, 0.0)`

but i think we need to handle that correctly instead of just reading some memory after the slice end hoping for the best

**Comment by Luni-4** [comment]
I agree, perhaps we could padding vectors which aren't multiple of 4

**Pull request merged**
