### PR TITLE
Add avx version of resampler

### PR DESCRIPTION
**Pull request by khodzha**

### CODE REVIEW

**Comment by khodzha** [comment]
some comparisons:
| | avx | sse3
| ------- | ----------- | ----------- |
| simple | `[1.4668 ms 1.4809 ms 1.4939 ms]` | `[2.2687 ms 2.3049 ms 2.3516 ms]` | 
| simple_dbl | `[4.5020 ms 4.6611 ms 4.8439 ms]` | `[9.4305 ms 9.7674 ms 10.023 ms]` |

**Comment by khodzha** [comment]
i can do it

**Comment by Luni-4** [comment]
@khodzha 

I just opened another PR :)

**Comment by Luni-4** [comment]
@khodzha 

You could fix the `avx2` clippy warnings in this PR and then rebase

**Comment by khodzha** [comment]
rebased + clippy fixes

**Pull request merged**
